#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType conformalVoronoiMesh
wmake $targetType conformalVoronoi2DMesh

[ $targetType = "objects" ] && execTargetType=$targetType
wmake $execTargetType foamyQuadMesh
wmake $execTargetType foamyHexMesh
#wmake $execTargetType foamyHexMeshBackgroundMesh
#(cd foamyHexMeshSurfaceSimplify && ./Allwmake $targetType $*)
#wmake $execTargetType cellSizeAndAlignmentGrid

#------------------------------------------------------------------------------
