#!/bin/sh
cd ${0%/*} || exit 1

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType DPMTurbulenceModels

[ $targetType = "objects" ] && execTargetType=$targetType
wmake $execTargetType
wmake $execTargetType MPPICFoam
