#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

wmake $targetType phaseChangeTwoPhaseMixtures

[ $targetType = "objects" ] && execTargetType=$targetType
wmake $execTargetType
wmake $execTargetType interPhaseChangeDyMFoam

#------------------------------------------------------------------------------
