#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

rm -rf 0 && cp -r 0.org 0

# Change patch type to 'patch' (was 'wall'). Not really necessary
for i in heater leftSolid rightSolid
do
   runApplication -s $i  changeDictionary -region $i
done


#-- Run on single processor
runApplication `getApplication`

## Decompose
#runApplication decomposePar -allRegions
#
## Run
#runParallel `getApplication`
#
## Reconstruct
#runApplication reconstructPar -allRegions


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

#------------------------------------------------------------------------------
